[target.aarch64-unknown-linux-musl]
rustflags = "-Ctarget-feature=+crt-static -Clink-self-contained=yes"

[target.x86_64-unknown-linux-musl]
rustflags = "-Ctarget-feature=+crt-static -Clink-self-contained=yes"
