name: Snapshots

on:
  workflow_run:
    workflows: [Rust]
    types:
      - completed

jobs:
  snapshot-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
    steps:
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: sensorfu/setup-rust-action@v1
        with:
          cache-key: cross-${{ matrix.target }}
      - run: cross build -v --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ledrama-sniffer-${{ matrix.target}}
          path: target/${{ matrix.target}}/release/ledrama-sniffer

  snapshot-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: sensorfu/setup-rust-action@v1
        with:
          cache-key: cargo-${{ matrix.target }}
      - run: cargo build -v --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ledrama-sniffer-${{ matrix.target}}
          path: target/${{ matrix.target}}/release/ledrama-sniffer
          if-no-files-found: error
